services:
  nginx-reverse-proxy:
    container_name: nginx-reverse-proxy
    build: .
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
